In [8]:
import statsmodels.formula.api as smf
import pandas as pd

salary_data = pd.read_csv('salary.csv')

# Remove Nan values
salary_data.dropna(how='any',axis=0)

salary_data.shape

lm = smf.ols(formula='yearsworked ~ salary', data=salary_data).fit() 

lm.params

display(salary_data)

,salary,exprior,yearsworked,yearsrank,market,degree,otherqual,position,male,Field,yearsabs
0,53000.00000,0,0,0,1.17,1,0,1,1,3,0
1,58000.00000,1,0,0,1.24,1,0,1,1,2,0
2,45500.00000,0,0,0,1.21,1,0,1,1,3,2
3,35782.00000,0,2,1,0.99,1,0,1,1,4,1
4,34731.00000,0,2,2,0.91,1,0,1,1,4,1
5,56000.00000,1,0,0,1.19,1,0,1,1,1,0
6,61008.00000,0,2,2,1.33,1,0,1,1,2,0
7,39986.00000,0,2,0,0.99,1,0,1,1,4,0
8,36308.00000,0,2,1,0.85,1,0,1,1,1,1
9,55000.00000,0,0,0,1.23,1,0,1,1,1,1
10,55227.00000,0,3,3,1.23,1,0,1,1,1,1
11,55227.00000,0,3,3,1.23,1,0,1,1,2,1
12,33680.00000,0,3,1,1.05,1,0,1,1,4,1
13,61008.00000,0,3,3,1.24,1,0,1,1,4,1
14,37000.00000,3,0,0,0.99,1,0,1,1,1,0
15,46292.00000,0,2,2,1.14,1,0,1,1,2,0
16,33680.00000,0,2,1,0.85,1,0,1,1,3,0
17,39754.00000,0,1,0,0.88,1,0,1,1,3,2
18,34000.00000,0,3,3,0.73,1,0,1,1,3,2
19,42614.00000,0,2,2,0.88,1,0,1,1,2,0
20,55121.00000,2,1,1,1.18,1,0,1,1,2,0
21,32000.00000,3,0,0,0.91,1,0,1,1,3,0
22,34731.00000,1,1,1,0.85,1,0,1,1,4,3
23,62059.00000,0,3,3,1.17,1,0,1,1,1,0
24,61008.00000,0,2,2,1.33,1,0,1,1,2,1
25,33680.00000,0,3,3,0.88,1,0,1,1,4,1
26,35206.00000,0,3,2,0.85,1,0,1,1,4,0
27,35257.00000,0,2,2,0.85,1,0,1,1,4,1
28,35782.00000,1,2,2,0.99,1,0,1,1,4,0
29,39000.00000,4,0,0,1.22,1,0,1,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...
484,42813.00000,6,10,7,0.85,1,0,2,0,2,47
485,50008.00000,0,18,10,0.80,1,0,2,0,1,47
486,52773.00000,0,28,14,0.88,1,0,2,0,1,48
487,34997.00000,0,18,12,0.80,1,0,2,0,3,49
488,43921.00000,0,17,11,0.85,1,0,2,0,3,49
489,38935.00000,15,3,3,0.91,1,0,1,0,4,49
490,51640.00000,4,13,5,0.99,1,0,3,0,4,49
491,60678.00000,5,13,0,1.21,1,0,3,0,1,50
492,63660.85156,17,1,1,0.92,1,1,3,0,2,50
493,44410.85547,7,12,10,0.72,1,0,2,0,3,51
494,50729.00000,0,20,7,0.85,1,0,3,0,2,52
495,58530.00000,0,19,9,0.93,1,0,3,0,2,52
496,41063.00000,1,18,18,0.81,1,0,1,0,4,52
497,48681.00000,0,19,12,1.05,1,0,2,0,4,52
498,52446.00000,5,14,6,0.81,1,0,3,0,4,52
499,45669.00000,2,18,5,0.73,1,0,2,0,3,56
500,45047.00000,0,20,20,0.83,1,0,1,0,1,56
501,50280.00000,0,22,15,0.85,1,0,2,0,2,58
502,48765.00000,10,11,4,0.94,1,0,3,0,4,58
503,36308.00000,16,5,5,0.86,1,0,1,0,1,60
504,64770.00000,0,25,15,1.02,1,0,3,0,1,62
505,52009.00000,0,23,1,0.85,1,0,3,0,2,63
506,46843.00000,0,23,13,0.81,1,0,2,0,3,65
507,58766.75781,0,23,12,0.99,1,1,3,0,2,67
508,52395.00000,5,19,7,0.86,1,0,3,0,4,69
509,45906.00000,6,17,11,0.92,1,0,2,0,2,70
510,60402.00000,6,19,7,0.86,1,0,3,0,1,72
511,53187.00000,19,7,6,0.78,1,0,3,0,4,76
512,56542.00000,8,20,10,0.78,1,0,3,0,2,78
513,52662.00000,13,25,11,0.78,1,0,3,0,1,112